/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EngineConfig = IDL.Record({
  'exitArea' : IDL.Float64,
  'fanPressureRatio' : IDL.Float64,
  'compressorEfficiency' : IDL.Float64,
  'exhaustVelocity' : IDL.Float64,
  'name' : IDL.Text,
  'bypassRatio' : IDL.Float64,
  'overallPressureRatio' : IDL.Float64,
  'ambientPressure' : IDL.Float64,
  'flightSpeed' : IDL.Float64,
  'exhaustPressure' : IDL.Float64,
  'massFlow' : IDL.Float64,
  'turbineInletTemp' : IDL.Float64,
  'turbineEfficiency' : IDL.Float64,
});
export const PerformanceResults = IDL.Record({
  'TSFC' : IDL.Float64,
  'fuelFlowRate' : IDL.Float64,
  'propulsiveEfficiency' : IDL.Float64,
  'overallEfficiency' : IDL.Float64,
  'thermalEfficiency' : IDL.Float64,
  'netThrust' : IDL.Float64,
  'specificThrust' : IDL.Float64,
});
export const Message = IDL.Record({
  'userMessage' : IDL.Text,
  'timestamp' : IDL.Int,
  'aiResponse' : IDL.Text,
});

export const idlService = IDL.Service({
  'addChatSession' : IDL.Func([IDL.Text], [], []),
  'addMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'calculatePerformance' : IDL.Func(
      [EngineConfig],
      [PerformanceResults],
      ['query'],
    ),
  'deleteChatSession' : IDL.Func([IDL.Text], [], []),
  'deleteConfig' : IDL.Func([IDL.Text], [], []),
  'getAllChatSessions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getChatHistory' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
  'getPerformance' : IDL.Func([IDL.Text], [PerformanceResults], ['query']),
  'listConfigs' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'loadConfig' : IDL.Func([IDL.Text], [EngineConfig], ['query']),
  'saveConfig' : IDL.Func([EngineConfig], [], []),
  'savePerformance' : IDL.Func([IDL.Text, PerformanceResults], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EngineConfig = IDL.Record({
    'exitArea' : IDL.Float64,
    'fanPressureRatio' : IDL.Float64,
    'compressorEfficiency' : IDL.Float64,
    'exhaustVelocity' : IDL.Float64,
    'name' : IDL.Text,
    'bypassRatio' : IDL.Float64,
    'overallPressureRatio' : IDL.Float64,
    'ambientPressure' : IDL.Float64,
    'flightSpeed' : IDL.Float64,
    'exhaustPressure' : IDL.Float64,
    'massFlow' : IDL.Float64,
    'turbineInletTemp' : IDL.Float64,
    'turbineEfficiency' : IDL.Float64,
  });
  const PerformanceResults = IDL.Record({
    'TSFC' : IDL.Float64,
    'fuelFlowRate' : IDL.Float64,
    'propulsiveEfficiency' : IDL.Float64,
    'overallEfficiency' : IDL.Float64,
    'thermalEfficiency' : IDL.Float64,
    'netThrust' : IDL.Float64,
    'specificThrust' : IDL.Float64,
  });
  const Message = IDL.Record({
    'userMessage' : IDL.Text,
    'timestamp' : IDL.Int,
    'aiResponse' : IDL.Text,
  });
  
  return IDL.Service({
    'addChatSession' : IDL.Func([IDL.Text], [], []),
    'addMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'calculatePerformance' : IDL.Func(
        [EngineConfig],
        [PerformanceResults],
        ['query'],
      ),
    'deleteChatSession' : IDL.Func([IDL.Text], [], []),
    'deleteConfig' : IDL.Func([IDL.Text], [], []),
    'getAllChatSessions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getChatHistory' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
    'getPerformance' : IDL.Func([IDL.Text], [PerformanceResults], ['query']),
    'listConfigs' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'loadConfig' : IDL.Func([IDL.Text], [EngineConfig], ['query']),
    'saveConfig' : IDL.Func([EngineConfig], [], []),
    'savePerformance' : IDL.Func([IDL.Text, PerformanceResults], [], []),
  });
};

export const init = ({ IDL }) => { return []; };