/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface EngineConfig {
  'exitArea' : number,
  'fanPressureRatio' : number,
  'compressorEfficiency' : number,
  'exhaustVelocity' : number,
  'name' : string,
  'bypassRatio' : number,
  'overallPressureRatio' : number,
  'ambientPressure' : number,
  'flightSpeed' : number,
  'exhaustPressure' : number,
  'massFlow' : number,
  'turbineInletTemp' : number,
  'turbineEfficiency' : number,
}
export interface Message {
  'userMessage' : string,
  'timestamp' : bigint,
  'aiResponse' : string,
}
export interface PerformanceResults {
  'TSFC' : number,
  'fuelFlowRate' : number,
  'propulsiveEfficiency' : number,
  'overallEfficiency' : number,
  'thermalEfficiency' : number,
  'netThrust' : number,
  'specificThrust' : number,
}
export interface _SERVICE {
  'addChatSession' : ActorMethod<[string], undefined>,
  'addMessage' : ActorMethod<[string, string, string], undefined>,
  'calculatePerformance' : ActorMethod<[EngineConfig], PerformanceResults>,
  'deleteChatSession' : ActorMethod<[string], undefined>,
  'deleteConfig' : ActorMethod<[string], undefined>,
  'getAllChatSessions' : ActorMethod<[], Array<string>>,
  'getChatHistory' : ActorMethod<[string], Array<Message>>,
  'getPerformance' : ActorMethod<[string], PerformanceResults>,
  'listConfigs' : ActorMethod<[], Array<string>>,
  'loadConfig' : ActorMethod<[string], EngineConfig>,
  'saveConfig' : ActorMethod<[EngineConfig], undefined>,
  'savePerformance' : ActorMethod<[string, PerformanceResults], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];