/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Message {
    userMessage: string;
    timestamp: bigint;
    aiResponse: string;
}
export interface PerformanceResults {
    TSFC: number;
    fuelFlowRate: number;
    propulsiveEfficiency: number;
    overallEfficiency: number;
    thermalEfficiency: number;
    netThrust: number;
    specificThrust: number;
}
export interface EngineConfig {
    exitArea: number;
    fanPressureRatio: number;
    compressorEfficiency: number;
    exhaustVelocity: number;
    name: string;
    bypassRatio: number;
    overallPressureRatio: number;
    ambientPressure: number;
    flightSpeed: number;
    exhaustPressure: number;
    massFlow: number;
    turbineInletTemp: number;
    turbineEfficiency: number;
}
export interface backendInterface {
    addChatSession(sessionId: string): Promise<void>;
    addMessage(sessionId: string, userMessage: string, aiResponse: string): Promise<void>;
    calculatePerformance(config: EngineConfig): Promise<PerformanceResults>;
    deleteChatSession(sessionId: string): Promise<void>;
    deleteConfig(name: string): Promise<void>;
    getAllChatSessions(): Promise<Array<string>>;
    getChatHistory(sessionId: string): Promise<Array<Message>>;
    getPerformance(name: string): Promise<PerformanceResults>;
    listConfigs(): Promise<Array<string>>;
    loadConfig(name: string): Promise<EngineConfig>;
    saveConfig(config: EngineConfig): Promise<void>;
    savePerformance(name: string, results: PerformanceResults): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addChatSession(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addChatSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChatSession(arg0);
            return result;
        }
    }
    async addMessage(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async calculatePerformance(arg0: EngineConfig): Promise<PerformanceResults> {
        if (this.processError) {
            try {
                const result = await this.actor.calculatePerformance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculatePerformance(arg0);
            return result;
        }
    }
    async deleteChatSession(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChatSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChatSession(arg0);
            return result;
        }
    }
    async deleteConfig(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteConfig(arg0);
            return result;
        }
    }
    async getAllChatSessions(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllChatSessions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllChatSessions();
            return result;
        }
    }
    async getChatHistory(arg0: string): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatHistory(arg0);
            return result;
        }
    }
    async getPerformance(arg0: string): Promise<PerformanceResults> {
        if (this.processError) {
            try {
                const result = await this.actor.getPerformance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPerformance(arg0);
            return result;
        }
    }
    async listConfigs(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.listConfigs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listConfigs();
            return result;
        }
    }
    async loadConfig(arg0: string): Promise<EngineConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.loadConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loadConfig(arg0);
            return result;
        }
    }
    async saveConfig(arg0: EngineConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveConfig(arg0);
            return result;
        }
    }
    async savePerformance(arg0: string, arg1: PerformanceResults): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePerformance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePerformance(arg0, arg1);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
